spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  threads:
    virtual:
      enabled: true
  application:
    name: FinnHubConnectorApplication

server:
  port: 8081

finnhub:
  url: wss://ws.finnhub.io
  symbols: AAPL,AMZN,BINANCE:BTCUSDT