spring:
  kafka:
    bootstrap-servers: localhost:9092
  config:
    import: "vault://secret/FinnHubConnectorApplication/local"
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      scheme: http
      kv:
        enabled: true
        backend: secret